name: security-semgrep

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  security-semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4              
      - name: Install Semgrep             
        run: pip3 install semgrep
      - name: Run Semgrep Scanner
        run: semgrep scan --json --output=semgrep-report.json || true

      - name: import scan results into defectdojo
        uses: portswigger-cloud/defectdojo-import-scan@v1.0.1
        with:
          ####  need backtrail / for URL otherwise pipeline will fail
          #### example: https://defectdojo.example.com/
          defectdojo-url: ${{ secrets.DEFECTDOJO_URL }}
          defectdojo-username: ${{ secrets.DEFECTDOJO_USERNAME }}
          defectdojo-password: ${{ secrets.DEFECTDOJO_PASSWORD }}
          defectdojo-product-type: github.com
          defectdojo-product: operation.repo
          defectdojo-environment-type: Production
          defectdojo-scan-type: Semgrep JSON Report
          defectdojo-engagement-name: operation.repo
          scan-results-file-name: semgrep-report.json
    
          