name: security-bandit

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  security-bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4              
      - name: Install  Bandit Scanner             
        run: pip3 install bandit
      - name: Run Bandit Scanner
        run: bandit -r . -f json -o bandit-report.json || true

      - name: import scan results into defectdojo
        uses: portswigger-cloud/defectdojo-import-scan@v1.0.1
        with:
          ####  need backtrail / for URL otherwise pipeline will fail
          #### example: https://defectdojo.example.com/
          defectdojo-url: ${{ secrets.DEFECTDOJO_URL }}
          defectdojo-username: ${{ secrets.DEFECTDOJO_USERNAME }}
          defectdojo-password: ${{ secrets.DEFECTDOJO_PASSWORD }}
          defectdojo-product-type: github.com
          defectdojo-product: operation.repo
          defectdojo-environment-type: Production
          defectdojo-scan-type: Bandit Scan
          defectdojo-engagement-name: operation.repo.ci.cd
          scan-results-file-name: bandit-report.json
    
          

      